"""
Package install information. 

This build script provides information about 
the `lib` package (e.g., the name and version, 
what should be included the built package, 
and etc.).
"""

import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="TVQ-Scripts",
    version="0.0.1",
    author="https://github.com/Genometric/TVQ/graphs/contributors",
    description="Scripts to post-process data generated by TVQ.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Genometric/TVQ",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.7',
)
