version: '3.8'

services:

  sql.data:
    environment:
      # - ID=SA
      - SA_PASSWORD=Pass_word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./Deployment/Database/mssql:/var/opt/mssql

  tvq:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_HTTPS_PORT=44376
      - SCOPUS_API_KEY=${SCOPUS_API_KEY}
    ports:
      - "8000:80"
#      - "44376:443"
    volumes:
      - ./Deployment/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./Deployment/ASP.NET/Https:/root/.aspnet/https:ro
