version: '3.8'

services:

  sql.data:
    environment:
      - SA_PASSWORD=Pass_word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./Deployment/Database/mssql:/var/opt/mssql

  tvq:
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SCOPUS_API_KEY=${SCOPUS_API_KEY}
    entrypoint: ["./entrypoint.sh", "sql.data:1433", "120"]
